---
abstract: 'Manage assets for Email'
author:
  - 'Aaron J Trevena <teejay@cpan.org>'
build_requires:
  File::Compare: '0'
  File::Temp: '0'
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.142060'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Email-Assets
no_index:
  directory:
    - t
    - inc
requires:
  MIME::Base64: '0'
  MIME::Types: '0'
  Moose: '0'
  perl: '5.006'
version: '0.01'
